name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on:
      group: enterprise/Default
      labels: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Biome lint
        run: pnpm lint
